TRAIN:
  PRE_TRAIN_EPOCHS: 100
  EPOCHS: 200
  LR: 0.005
  DECAY_RATE: 0.99
  DECAY_STEP: 300

SETTING:
  NETWORK: 'MACNN_SE_m'
  LOSS: 'EWLoss'
  DISTANCE: 'L2'
  TRAIN_DATASET: 'fmitdb'
  TEST_DATASET: 'incartdb'
  CENTER: False
  ASPP_BN: True
  ASPP_ACT: True
  RE_TRAIN: False
  NORM_ALIGN: True
  BEAT_NUM: 0
  UDA_NUM: 1000
  FIXED_LEN: 128
  INTER_LOSS: True
  INTRA_LOSS: True
  DILATIONS: (1, 6, 12, 18)
  ACT: 'relu'
  F_ACT: 'relu'
  CORAL: True
  SEED: 14124

PARAMETERS:
  W_L2: 0.0001
  W_CORAL: 10.0
  BETA1: 0.1
  BETA2: 0.1
  BETA: 0.5
  BETA_MMD: 0.01
  BETA_INTER: 0.05
  BETA_INTRA: 0.01
  THR_M: 5.0
  THRS: (0.999, 0.99, 0.85, 0.99)
