# acnn/acnn_mitdb_mitdb_1_300_200_cb_cosine.yaml

TRAIN:
  PRE_TRAIN_EPOCHS: 200
  EPOCHS: 500
  LR: 0.01
  DECAY_RATE: 0.95
  DECAY_STEP: 300

SETTING:
  NETWORK: 'MACNN_SE'
  LOSS: 'EWLoss'
  DISTANCE: 'Cosine'
  CENTER: False
  ASPP_BN: True
  ASPP_ACT: True
  RE_TRAIN: False
  NORM_ALIGN: False
  BEAT_NUM: 0
  FIXED_LEN: 128
  INTER_LOSS: True
  INTRA_LOSS: True
  DILATIONS: (1, 6, 12, 18)
  ACT: 'relu'

PARAMETERS:
  W_L2: 0.0001
  THRS: (0.99, 0.99, 0.99, 0.99)
